backend:
  # name: git-gateway
  # branch: master
  #name: github
  #repo: RedRichard/letrast-gatsby
  #name: test-repo
  name: github
  repo: RedRichard/letrast-gatsby
  branch: testing

media_folder: static/assets
public_folder: /assets

collections:
  - name: post
    label: Post
    folder: content/posts
    create: true
    slug: "{{year}}-{{month}}-{{day}}_{{postTitle}}"
    preview_path: "{{postCategory}}/{{postSlug}}"
    fields:
      - { name: postTitle, label: Title, required: true }
      - {
          name: postSlug,
          label: Slug,
          hint: "Sólo minúsculas y guiones en lugar de espacios",
          required: true,
          pattern:
            ['^[a-z\-]+$', "Sólo minúsculas y guiones en lugar de espacios"],
        }
      - { name: postSubtitle, label: subtitle, required: true }
      - { name: body, label: Body, widget: markdown, required: true }
      - { name: postImage, label: Image, widget: string, required: true }
      - { name: postDate, label: Date, widget: datetime, required: true }
      - {
          widget: relation,
          name: postAuthor,
          label: Autor,
          collection: "author",
          valueField: "authorSlug",
          required: true,
          searchFields: ["authorSlug"],
          displayFields: ["authorSlug"],
        }
      - {
          widget: relation,
          name: postCategory,
          label: Categoría,
          collection: category,
          valueField: categorySlug,
          required: true,
          multiple: true,
          searchFields: ["categorySlug"],
          displayFields: ["categorySlug"],
        }

  - name: category
    label: Category
    folder: content/categories
    create: true
    slug: "{{year}}-{{month}}-{{day}}_{{categoryTitle}}"
    preview_path: "categorias/{{categoryTitle}}"
    fields:
      - { name: categoryTitle, label: Categoría, required: true }
      - {
          name: categorySlug,
          label: Slug,
          hint: "Sólo minúsculas y guiones en lugar de espacios",
          required: true,
          pattern:
            ['^[a-z\-]+$', "Sólo minúsculas y guiones en lugar de espacios"],
        }
      - {
          widget: relation,
          name: categoryPosts,
          label: Posts,
          collection: "post",
          valueField: "postSlug",
          required: false,
          multiple: true,
          searchFields: ["postSlug"],
          displayFields: ["postSlug"],
        }

  - name: author
    label: Author
    folder: content/authors
    create: true
    slug: "{{year}}-{{month}}-{{day}}_{{authorName}}"
    preview_path: "autores/{{authorName}}"
    fields:
      - { name: authorName, label: Nombre, widget: string, required: true }
      - {
          name: authorSlug,
          label: Slug,
          hint: "Sólo minúsculas y guiones en lugar de espacios",
          required: true,
          pattern:
            ['^[a-z\-]+$', "Sólo minúsculas y guiones en lugar de espacios"],
        }
      - { name: body, label: Bio, widget: string, required: true }
      - {
          widget: relation,
          name: posts,
          label: Posts,
          collection: "post",
          valueField: "postSlug",
          required: false,
          multiple: true,
          searchFields: ["postSlug"],
          displayFields: ["postSlug"],
        }
