backend:
  #name: git-gateway
  #branch: master
  #name: github
  #repo: RedRichard/letrast-gatsby
  #name: test-repo
  name: github
  repo: RedRichard/letrast-gatsby
  branch: performanceImprovements

media_folder: static/assets
public_folder: /assets

collections:
  - name: post
    label: Post
    folder: content/posts
    create: true
    slug: "{{year}}-{{month}}-{{day}}_{{postTitle}}"
    preview_path: "{{postCategory}}/{{postSlug}}"
    fields:
      - { name: postTitle, label: Title, required: true }
      - {
          name: postSlug,
          label: Slug,
          hint: "Sólo minúsculas y guiones en lugar de espacios",
          required: true,
          pattern:
            ['^[a-z\-]+$', "Sólo minúsculas y guiones en lugar de espacios"],
        }
      - { name: postSubtitle, label: subtitle, required: true }
      - { name: body, label: Body, widget: markdown, required: true }
      - {
          name: postImage,
          label: "Imagen principal",
          widget: image,
          required: true,
        }
      - { name: postDate, label: Date, widget: datetime, required: true }
      - {
          widget: relation,
          name: postAuthor,
          label: Autor,
          collection: "author",
          valueField: "authorSlug",
          required: true,
          searchFields: ["authorSlug"],
          displayFields: ["authorSlug"],
        }
      - {
          widget: relation,
          name: postCategory,
          label: Categoría,
          collection: category,
          valueField: categorySlug,
          required: true,
          multiple: false,
          searchFields: ["categorySlug"],
          displayFields: ["categorySlug"],
        }

  - name: category
    label: Category
    folder: content/categories
    create: true
    slug: "{{year}}-{{month}}-{{day}}_{{categoryTitle}}"
    preview_path: "categorias/{{categoryTitle}}"
    fields:
      - { name: categoryTitle, label: Categoría, required: true }
      - {
          name: categorySlug,
          label: Slug,
          hint: "Sólo minúsculas y guiones en lugar de espacios",
          required: true,
          pattern:
            ['^[a-z\-]+$', "Sólo minúsculas y guiones en lugar de espacios"],
        }
      - {
          widget: relation,
          name: categoryPosts,
          label: Posts,
          collection: "post",
          valueField: "postSlug",
          required: false,
          multiple: true,
          searchFields: ["postSlug"],
          displayFields: ["postSlug"],
        }

  - name: author
    label: Author
    folder: content/authors
    create: true
    slug: "{{year}}-{{month}}-{{day}}_{{authorName}}"
    preview_path: "autores/{{authorName}}"
    fields:
      - { name: authorName, label: Nombre, widget: string, required: true }
      - {
          name: authorSlug,
          label: Slug,
          hint: "Sólo minúsculas y guiones en lugar de espacios",
          required: true,
          pattern:
            ['^[a-z\-]+$', "Sólo minúsculas y guiones en lugar de espacios"],
        }
      - { name: body, label: Bio, widget: string, required: true }
      - {
          name: authorImage,
          label: "Imagen de perfil",
          widget: image,
          required: true,
        }
      - {
          name: authorTwitter,
          label: "Twitter",
          widget: string,
          required: false,
          hint: "Sólo el nombre de usuario, sin el @",
          default: "",
        }
      - {
          name: authorInstagram,
          label: "Instagram",
          widget: string,
          required: false,
          hint: "Sólo el nombre de usuario",
          default: "",
        }
      - {
          name: authorFacebook,
          label: "Facebook",
          widget: string,
          required: false,
          hint: "Sólo el nombre de usuario",
          default: "",
        }
      - {
          widget: relation,
          name: posts,
          label: Posts,
          collection: "post",
          valueField: "postSlug",
          required: false,
          multiple: true,
          searchFields: ["postSlug"],
          displayFields: ["postSlug"],
        }

  - label: "Configuración Global"
    name: "pages"
    files:
      - label: "Acerca de"
        name: "about"
        file: "content/config/aboutPage.md"
        fields:
          - { name: aboutTitle, label: Title, required: true }
          - { name: body, label: Body, widget: markdown, required: true }
          - { name: aboutImage, label: Image, widget: string, required: true }

      - label: "Social Media"
        name: "social"
        file: "content/config/globalConfig.md"
        fields:
          - {
              name: siteTwitter,
              label: "Twitter",
              widget: string,
              required: false,
              hint: "Sólo el nombre de usuario, sin el @",
              default: "",
            }
          - {
              name: siteInstagram,
              label: "Instagram",
              widget: string,
              required: false,
              hint: "Sólo el nombre de usuario",
              default: "",
            }
          - {
              name: siteFacebook,
              label: "Facebook",
              widget: string,
              required: false,
              hint: "Sólo el nombre de usuario",
              default: "",
            }
