backend:
  # For Netlify Identity:
  # name: git-gateway
  # branch: master
  repo: your-username/your-repository-name
  branch: master

media_folder: static/assets
public_folder: /assets

collections:
  - name: post
    label: Post
    folder: content/posts
    create: true
    slug: "{{year}}-{{month}}-{{day}}_{{postTitle}}"
    preview_path: "{{postCategory}}/{{postSlug}}"
    fields:
      - { name: postTitle, label: Title, required: true }
      - {
          name: postSlug,
          label: Slug,
          hint: "Only lowercase letters and dashes",
          required: true,
          pattern: ['^[a-z\-]+$', "Only lowercase letters and dashes"],
        }
      - { name: postSubtitle, label: subtitle, required: true }
      - { name: body, label: Body, widget: markdown, required: true }
      - {
          name: postImage,
          label: "Main image",
          widget: image,
          required: true,
          hint: "Images of less than 1mb improve performance",
        }
      - { name: postDate, label: Date, widget: datetime, required: true }
      - {
          widget: relation,
          name: postAuthor,
          label: Author,
          collection: "author",
          valueField: "authorSlug",
          required: true,
          searchFields: ["authorSlug"],
          displayFields: ["authorSlug"],
        }
      - {
          widget: relation,
          name: postCategory,
          label: Category,
          collection: category,
          valueField: categorySlug,
          required: true,
          multiple: false,
          searchFields: ["categorySlug"],
          displayFields: ["categorySlug"],
        }

  - name: category
    label: Category
    folder: content/categories
    create: true
    slug: "{{year}}-{{month}}-{{day}}_{{categoryTitle}}"
    preview_path: "categorias/{{categoryTitle}}"
    fields:
      - { name: categoryTitle, label: Categoría, required: true }
      - {
          name: categorySlug,
          label: Slug,
          hint: "Only lowercase letters and dashes",
          required: true,
          pattern: ['^[a-z\-]+$', "Only lowercase letters and dashes"],
        }
      - {
          widget: relation,
          name: categoryPosts,
          label: Posts,
          collection: "post",
          valueField: "postSlug",
          required: false,
          multiple: true,
          searchFields: ["postSlug"],
          displayFields: ["postSlug"],
        }

  - name: author
    label: Author
    folder: content/authors
    create: true
    slug: "{{year}}-{{month}}-{{day}}_{{authorName}}"
    preview_path: "autores/{{authorName}}"
    fields:
      - { name: authorName, label: Nombre, widget: string, required: true }
      - {
          name: authorSlug,
          label: Slug,
          hint: "Only lowercase letters and dashes",
          required: true,
          pattern: ['^[a-z\-]+$', "Only lowercase letters and dashes"],
        }
      - { name: body, label: Bio, widget: string, required: true }
      - {
          name: authorImage,
          label: "Profile picture",
          widget: image,
          required: true,
        }
      - {
          name: authorTwitter,
          label: "Twitter",
          widget: string,
          required: false,
          hint: "Handler",
          default: "",
        }
      - {
          name: authorInstagram,
          label: "Instagram",
          widget: string,
          required: false,
          hint: "Username",
          default: "",
        }
      - {
          name: authorFacebook,
          label: "Facebook",
          widget: string,
          required: false,
          hint: "Username",
          default: "",
        }
      - {
          widget: relation,
          name: posts,
          label: Posts,
          collection: "post",
          valueField: "postSlug",
          required: false,
          multiple: true,
          searchFields: ["postSlug"],
          displayFields: ["postSlug"],
        }

  - label: "Global Config"
    name: "pages"
    files:
      - label: "About"
        name: "about"
        file: "content/config/aboutPage.md"
        fields:
          - { name: aboutTitle, label: Title, required: true }
          - { name: body, label: Body, widget: markdown, required: true }
          - { name: aboutImage, label: Image, widget: image, required: true }

      - label: "Social Media"
        name: "social"
        file: "content/config/globalConfig.md"
        fields:
          - {
              name: siteTwitter,
              label: "Twitter",
              widget: string,
              required: false,
              hint: "Handler",
              default: "",
            }
          - {
              name: siteInstagram,
              label: "Instagram",
              widget: string,
              required: false,
              hint: "Username",
              default: "",
            }
          - {
              name: siteFacebook,
              label: "Facebook",
              widget: string,
              required: false,
              hint: "Username",
              default: "",
            }
